function init(self)
	local center_anchor = vmath.vector3(0, 0, 0)
	local lower_anchor = vmath.vector3(0, -64, 0)

	local hinge_props = {
		enable_limit = true,
		lower_angle = math.rad(-20),
		upper_angle = math.rad(20),
	}

	physics.create_joint(
		physics.JOINT_TYPE_HINGE,
		"upper#dynamic",
		"body_joint",
		center_anchor,
		"lower#dynamic",
		lower_anchor,
		hinge_props
	)

	self.upper_body_pos = vmath.vector3()
end
