components {
  id: "npc_part"
  component: "/main/npc/npc_part.script"
}
embedded_components {
  id: "part"
  type: "sprite"
  data: "default_animation: \"upper\"\n"
  "material: \"/render/sprite/sprite.material\"\n"
  "size {\n"
  "  x: 128.0\n"
  "  y: 128.0\n"
  "}\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/assets/npc.tilesource\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "dynamic"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 1.0\n"
  "friction: 0.7\n"
  "restitution: 0.25\n"
  "group: \"npc_part\"\n"
  "mask: \"tile\"\n"
  "mask: \"npc_part\"\n"
  "mask: \"hand\"\n"
  "mask: \"player_trigger\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      y: -24.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 1\n"
  "  }\n"
  "  data: 40.0\n"
  "}\n"
  ""
}
